---
# default vars for jetty role
# CHANGE THEM ONLY IF YOU KNOW WHAT YOU ARE DOING

# Jetty 12 - Shibboleth v5.x
jetty_distribution: "12.1.3"
jetty_logback_lib_version: "1.5.21"
jetty_requestlog_file: "jetty-requestlog.xml"
jetty_start_ini: "files/java{{ jdk_version }}/start.ini"
